/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppPantryRouteImport } from './routes/_app.pantry'
import { Route as AppListRouteImport } from './routes/_app.list'
import { Route as AppPantryItemIdRouteImport } from './routes/_app.pantry_.$itemId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppListRoute = AppListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryItemIdRoute = AppPantryItemIdRouteImport.update({
  id: '/pantry_/$itemId',
  path: '/pantry/$itemId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/list': typeof AppListRoute
  '/pantry': typeof AppPantryRoute
  '/shop': typeof AppShopRoute
  '/pantry/$itemId': typeof AppPantryItemIdRoute
}
export interface FileRoutesByTo {
  '/list': typeof AppListRoute
  '/pantry': typeof AppPantryRoute
  '/shop': typeof AppShopRoute
  '/': typeof AppIndexRoute
  '/pantry/$itemId': typeof AppPantryItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/list': typeof AppListRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pantry_/$itemId': typeof AppPantryItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list' | '/pantry' | '/shop' | '/pantry/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/list' | '/pantry' | '/shop' | '/' | '/pantry/$itemId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/list'
    | '/_app/pantry'
    | '/_app/shop'
    | '/_app/'
    | '/_app/pantry_/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/list': {
      id: '/_app/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof AppListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry_/$itemId': {
      id: '/_app/pantry_/$itemId'
      path: '/pantry/$itemId'
      fullPath: '/pantry/$itemId'
      preLoaderRoute: typeof AppPantryItemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppListRoute: typeof AppListRoute
  AppPantryRoute: typeof AppPantryRoute
  AppShopRoute: typeof AppShopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPantryItemIdRoute: typeof AppPantryItemIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppListRoute: AppListRoute,
  AppPantryRoute: AppPantryRoute,
  AppShopRoute: AppShopRoute,
  AppIndexRoute: AppIndexRoute,
  AppPantryItemIdRoute: AppPantryItemIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
